services:
  emby-doom-addon:
    build: .
    container_name: emby-doom-addon
    restart: unless-stopped
    environment:
      HOST: 0.0.0.0
      PORT: 7000
      EMBY_DEFAULT_MODE: auto
      FLIXNEST_ADDON_URL: https://flixnest.app/flix-streams/u/6p9xzp78nunz
      FLIXNEST_TIMEOUT_MS: 30000
      EMBY_PROVIDER_IDS: flixnest
      EMBY_FAST_PROVIDER_IDS: flixnest
      EMBY_SLOW_PROVIDER_IDS: flixnest
      EMBY_FALLBACK_PROVIDER_IDS: flixnest
      EMBY_WAIT_PROVIDER_IDS: flixnest
      EMBY_QUICK_RESOLVE_TIMEOUT_MS: 7000
      EMBY_QUICK_PROVIDER_TIMEOUT_MS: 7000
      EMBY_QUICK_MIN_CANDIDATES: 1
      EMBY_QUICK_VALIDATE_CANDIDATES: 4
      STREAM_CACHE_TTL_MS: 240000
      EMBY_VALIDATE_CONCURRENCY: 8
      EMBY_VALIDATE_CANDIDATES: 10
      FLIX_STREAMS_TIMEOUT_MS: 30000
    ports:
      - "7001:7000"
